#!/usr/bin/env python3
"""
DEPRECATED (2026-07-21): superseded by the in-repo lab/ (lab.runner, versioned
mechanisms, reproduction gate). This module still uses the bittensor 9.x API,
which cannot decode the spec-430+ runtime — port to chain_compat before any
reuse. Nothing imports it; kept for historical reference only.

Root Reborn (subtensor PR #2759) — SN21 risk models
=====================================================
Two models:
  A. Redemption overhang & cascade price impact  (risk R-C, primary)
  B. Two-way reflexivity sketch via Taoflow       (risk R-D, gated)

AMM assumption: constant-product pool  T * A = k,  spot price p = T / A
(TAO per alpha). Selling dA alpha:
    p1 / p0 = ( A0 / (A0 + dA) )**2 = ( 1 / (1 + x) )**2 ,  x = dA / A0
So price impact depends ONLY on the sell size as a fraction of the
alpha reserve. That makes the model robust even where absolute reserve
figures are uncertain — what matters is the ratio.

USAGE
-----
  python root_reborn_model.py                 # run on baked-in last-known LIVE state
  python root_reborn_model.py --live          # pull fresh SN21 + market state, then run
  python root_reborn_model.py --live --write-doc
                                              # also regenerate the auto block in
                                              # docs/Root_Reborn_SN21_Risk_Assessment.md

The pool-state inputs (alpha_reserve, alpha_price_tao, tao reserve) and the §6
market-context figures (liquidity rank, price rank, root-stake concentration)
are LIVE: defaults below are the last on-chain pull; --live refreshes them from
the same finney path market_sync.py / collector.py use.

The flow inputs (network_root_div_tao_day, sn21_weight_share, accumulation_days,
baseline_rootprop_sell_alpha_day) are NOT chain-readable in the current RPC
version (subnet(21) emission fields return 0). They remain ESTIMATE / SCENARIO
knobs — edit them here.
"""

import sys
import statistics
from datetime import datetime, timezone
from pathlib import Path

# ----------------------------------------------------------------------
# INPUTS
#   pool block: LIVE-BACKED (see DEFAULTS_SOURCE); refresh with --live
#   flow block: ESTIMATE / SCENARIO — not chain-readable
# ----------------------------------------------------------------------
DEFAULTS_SOURCE = "finney all_subnets() @ block 8,432,852 · 2026-06-18"

INPUTS = {
    # --- SN21 AMM pool (LIVE-BACKED — refresh with --live) ---
    "alpha_reserve":            1_974_778.0,   # alpha_in of the SN21 pool      [LIVE]
    "alpha_price_tao":          0.00405200,    # spot = tao_in / alpha_in       [LIVE]
    "dereg_floor_tao":          None,          # resolved LIVE — see resolve_dereg_floor()

    # --- Root Reborn buy-flow into SN21 (ESTIMATE / SCENARIO — not chain-readable) ---
    "network_root_div_tao_day": 1500.0,        # TOTAL TAO/day recycled across ALL baskets [ESTIMATE]
    "sn21_weight_share":        0.01,          # SN21's aggregate share of all root baskets [SCENARIO]
    "accumulation_days":        30,            # days the basket builds before a cascade    [SCENARIO]

    # --- Today's baseline for comparison (ESTIMATE — not chain-readable) ---
    "baseline_rootprop_sell_alpha_day": 50.0,  # current daily root-prop alpha sold on SN21  [ESTIMATE]
}

NETUID_SN21 = 21

# The dereg floor is NOT a constant. The chain dissolves whichever NON-IMMUNE
# subnet has the lowest EMA alpha price whenever someone registers a new subnet
# (get_network_to_prune, coinbase/root.rs) — so "the floor" is that subnet's EMA
# and it re-ranks continuously. dereg_watch.py reads it live every 2 days; this
# fallback is used only if the watch has never run, and says so in the report.
DEREG_FLOOR_FALLBACK = 0.00195     # netuid 103's EMA @ block 8,727,955 (2026-07-29)
DOC_PATH = Path(__file__).resolve().parent / "docs" / "Root_Reborn_SN21_Risk_Assessment.md"
DOC_MARK_BEGIN = "<!-- BEGIN live-figures (auto-generated by root_reborn_model.py --write-doc — do not edit by hand) -->"
DOC_MARK_END = "<!-- END live-figures -->"


# ----------------------------------------------------------------------
# LIVE FETCH  — same finney path as market_sync.py / collector.py
# ----------------------------------------------------------------------
def _to_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        for attr in ("tao", "rao"):
            v = getattr(x, attr, None)
            if v is not None:
                return float(v) / (1e9 if attr == "rao" else 1.0)
    return None


def resolve_dereg_floor(cfg: dict | None = None) -> tuple[float, str]:
    """Live dereg floor: the EMA of whichever non-immune subnet is currently first
    in the prune queue. Returns (floor, provenance) — provenance is printed so a
    stale fallback can never be mistaken for a live read."""
    from dereg_watch import load_dereg_state

    if cfg and cfg.get("dereg_floor_tao"):
        return float(cfg["dereg_floor_tao"]), "explicit override"
    d = load_dereg_state()
    if d.get("floor_tao"):
        return float(d["floor_tao"]), (
            f"LIVE — netuid {d.get('floor_netuid')} is the prune target, "
            f"read {str(d.get('checked_at'))[:10]}"
        )
    return DEREG_FLOOR_FALLBACK, "STALE FALLBACK — run dereg_watch.py"


def fetch_live(netuid: int = NETUID_SN21, floor: float | None = None) -> dict:
    """One finney connection -> SN21 pool state + §6 market context + root-stake
    concentration. Raises on failure so --live never silently uses stale values."""
    # Ported to raw storage (2026-07-22): bittensor 9.x's all_subnets() can't
    # decode the spec-430 runtime and bittensor 11 has no bulk pool read.
    from chain_compat import qmap, substrate

    if floor is None:
        floor, _ = resolve_dereg_floor()

    with substrate() as sub:
        block = int(sub.get_block_number(sub.get_chain_head()))
        tao_map = qmap(sub, "SubnetTAO", 1e9)
        alpha_map = qmap(sub, "SubnetAlphaIn", 1e9)

    rows = []
    for nu in sorted(set(tao_map) | set(alpha_map)):
        if nu == 0:  # root has no alpha pool
            continue
        tao_in = tao_map.get(nu)
        alpha_in = alpha_map.get(nu)
        price = (tao_in / alpha_in) if (tao_in and alpha_in and alpha_in > 0) else None
        if not price or price <= 0:
            continue
        rows.append({"netuid": nu, "tao_in": tao_in, "alpha_in": alpha_in, "price": price})

    sn21 = next((r for r in rows if r["netuid"] == netuid), None)
    if sn21 is None:
        raise RuntimeError(f"netuid {netuid} pool not found / invalid in all_subnets()")

    n = len(rows)
    by_tao = sorted(rows, key=lambda r: r["tao_in"])
    by_price = sorted(rows, key=lambda r: r["price"])

    def rank(lst):
        idx = next(i for i, r in enumerate(lst) if r["netuid"] == netuid)
        return idx + 1, round(100 * (idx + 1) / len(lst), 1)

    taos = [r["tao_in"] for r in rows]
    prices = [r["price"] for r in rows]
    tao_rank, tao_pct = rank(by_tao)
    price_rank, price_pct = rank(by_price)
    tao_median = statistics.median(taos)
    top_decile = sorted(taos)[int(0.9 * n)]

    # Root-stake concentration (netuid 0) -> R-E / Q2
    root = None
    try:
        from chain_compat import fetch_metagraph

        mg0 = fetch_metagraph(0)
        stakes = sorted((float(s) for s in mg0.S), reverse=True)
        tot = sum(stakes) or 1.0
        root = {
            "n": len(stakes),
            "total": tot,
            **{f"top{k}": round(100 * sum(stakes[:k]) / tot, 1) for k in (1, 3, 4, 5, 10)},
        }
    except Exception as e:  # noqa: BLE001
        root = {"error": str(e)}

    return {
        "block": block,
        "pool": {
            "alpha_reserve": sn21["alpha_in"],
            "tao_reserve": sn21["tao_in"],
            "alpha_price_tao": sn21["price"],
        },
        "market": {
            "n_priced": n,
            "tao_in": sn21["tao_in"],
            "tao_rank": tao_rank, "tao_pct": tao_pct,
            "tao_median": tao_median, "tao_ratio_median": sn21["tao_in"] / tao_median,
            "tao_top_decile": top_decile, "in_top_decile": sn21["tao_in"] >= top_decile,
            "price": sn21["price"],
            "price_rank": price_rank, "price_pct": price_pct,
            "price_median": statistics.median(prices),
            "floor": floor,
            "spot_above_floor_pct": (sn21["price"] / floor - 1) * 100,
            "n_below_floor": sum(1 for p in prices if p < floor),
            "root": root,
        },
    }


# Back-compat thin wrapper (pool only).
def fetch_live_pool(netuid: int = NETUID_SN21) -> dict:
    live = fetch_live(netuid)
    return {"block": live["block"], **live["pool"]}


# ----------------------------------------------------------------------
# CORE AMM MATH  (shared with the lab — see lab/amm.py)
# ----------------------------------------------------------------------
from lab.amm import price_impact, overhang_alpha, floor_breach_overhang_ratio  # noqa: E402,F401


# ----------------------------------------------------------------------
# STDOUT REPORT
# ----------------------------------------------------------------------
def banner(t):
    print("\n" + "=" * 68 + f"\n{t}\n" + "=" * 68)

def run(cfg=INPUTS, source: str = DEFAULTS_SOURCE):
    A0 = cfg["alpha_reserve"]
    p0 = cfg["alpha_price_tao"]
    floor, floor_src = resolve_dereg_floor(cfg)
    T0 = p0 * A0

    banner(f"POOL SNAPSHOT  (pool state: {source})")
    print(f"  alpha reserve A0        : {A0:,.0f}")
    print(f"  spot price p0           : {p0:.5f} TAO/alpha")
    print(f"  implied TAO reserve T0  : {T0:,.0f} TAO")
    print(f"  dereg floor             : {floor:.5f} TAO/alpha  ({(floor/p0-1)*100:+.1f}% from spot)")
    print(f"    └ {floor_src}")

    P, a_day, tao_day = overhang_alpha(
        cfg["network_root_div_tao_day"], cfg["sn21_weight_share"], p0, cfg["accumulation_days"])
    x_over = P / A0
    banner(f"MODEL A — OVERHANG ACCUMULATED IN {cfg['accumulation_days']} DAYS "
           f"@ {cfg['sn21_weight_share']*100:.2f}% weight share  [flow inputs = ESTIMATE]")
    print(f"  daily buy-flow into SN21: {tao_day:,.1f} TAO/day  (~{a_day:,.0f} alpha/day)")
    print(f"  accumulated overhang    : {P:,.0f} alpha")
    print(f"  overhang / reserve (x)  : {x_over*100:.2f}%")

    banner("CASCADE PRICE IMPACT  (overhang sold back into pool over a short window)")
    print(f"  {'redeemed':>10} | {'alpha sold':>12} | {'x=sold/A0':>10} | {'price impact':>13} | {'spot after':>11} | breaches floor?")
    print("  " + "-" * 84)
    for f in (0.10, 0.25, 0.50, 1.00):
        sold = f * P
        x = sold / A0
        imp = price_impact(x)
        spot_after = p0 * (1 + imp)
        breach = "YES" if spot_after <= floor else "no"
        print(f"  {f*100:9.0f}% | {sold:12,.0f} | {x*100:9.2f}% | {imp*100:12.2f}% | {spot_after:11.5f} | {breach}")

    banner("BASELINE COMPARISON  (today's smooth root-prop sell — ESTIMATE)")
    q = cfg["baseline_rootprop_sell_alpha_day"]
    x_base = q / A0
    imp_base = price_impact(x_base)
    print(f"  baseline daily sell     : {q:,.0f} alpha/day")
    print(f"  daily price impact      : {imp_base*100:.4f}%  (spread across ~7,200 blocks => negligible intraday)")
    equiv_days = P / q if q else float('inf')
    print(f"  a FULL cascade ({P:,.0f} alpha) compresses ~{equiv_days:,.0f} days "
          f"of baseline selling into one window")

    banner("FLOOR-BREACH ANALYSIS  (full one-shot cascade)")
    x_breach = floor_breach_overhang_ratio(p0, floor)
    print(f"  overhang ratio that breaches floor on full cascade : {x_breach*100:.2f}% of reserve")
    print(f"  {'weight share':>13} | {'alpha/day':>10} | {'x/day':>8} | days to breach-capable overhang")
    print("  " + "-" * 70)
    for s in (0.005, 0.01, 0.02, 0.05):
        a_d = cfg["network_root_div_tao_day"] * s / p0
        x_d = a_d / A0
        days = x_breach / x_d if x_d else float('inf')
        print(f"  {s*100:12.1f}% | {a_d:10,.0f} | {x_d*100:7.3f}% | {days:6.0f} days")

    banner("SENSITIVITY — OVERHANG RATIO x  (rows = days, cols = weight share)")
    shares = (0.005, 0.01, 0.02, 0.05)
    print("  days\\share | " + " | ".join(f"{s*100:5.1f}%" for s in shares))
    print("  " + "-" * 52)
    for d in (14, 30, 60, 90):
        cells = [f"{overhang_alpha(cfg['network_root_div_tao_day'], s, p0, d)[0]/A0*100:5.1f}%" for s in shares]
        print(f"  {d:9d} | " + " | ".join(cells))

    banner("MODEL B — TWO-WAY REFLEXIVITY (DIRECTIONAL, GATED ON OPEN QUESTION Q1)")
    print("  If basket buys COUNT as Taoflow net inflow (Q1 = YES), buy-flow B raises")
    print("  emission share, which raises root dividend minted on SN21, which raises B:")
    print("      B_eff ~= B / (1 - e)      e = Taoflow elasticity of emission share to inflow")
    for e in (0.0, 0.2, 0.4):
        print(f"      e={e:.1f}  =>  amplification {1.0/(1.0-e):.2f}x  (up-spiral AND down-spiral)")
    print("  e is UNKNOWN here. If Q1 = NO (buys excluded, like legacy root-claim swaps),")
    print("  amplification = 1.0x and reflexivity is muted. RESOLVE Q1 BEFORE MODELLING.")

    print(f"\n[pool state: {source} · flow inputs ESTIMATE/SCENARIO — see module docstring]")


# ----------------------------------------------------------------------
# MARKDOWN BLOCK  (regenerated into the assessment doc by --write-doc)
# ----------------------------------------------------------------------
def render_live_block(cfg, source: str, market: dict | None = None) -> str:
    A0 = cfg["alpha_reserve"]
    p0 = cfg["alpha_price_tao"]
    floor, floor_src = resolve_dereg_floor(cfg)
    T0 = p0 * A0
    P, _, tao_day = overhang_alpha(
        cfg["network_root_div_tao_day"], cfg["sn21_weight_share"], p0, cfg["accumulation_days"])
    x_breach = floor_breach_overhang_ratio(p0, floor)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    L = []
    L.append(DOC_MARK_BEGIN)
    L.append(f"*Source: {source} · generated {stamp}. Regenerate with "
             f"`python root_reborn_model.py --live --write-doc`. Flow inputs "
             f"(root-dividend recycle, weight share, baseline sell) are ESTIMATE/SCENARIO — not chain-readable.*")
    L.append("")
    L.append("**Pool state (LIVE):**")
    L.append("")
    L.append("| Metric | Value |")
    L.append("|--------|-------|")
    L.append(f"| alpha reserve `A0` | {A0:,.0f} |")
    L.append(f"| TAO reserve `T0` (`tao_in`) | {T0:,.0f} TAO |")
    L.append(f"| spot price `p0` | {p0:.7f} TAO/alpha |")
    L.append(f"| dereg floor — {floor_src} | {floor:.5f} TAO/alpha ({(p0/floor-1)*100:+.1f}% headroom) |")
    L.append("")

    if market and "root" in market:
        m = market
        L.append("**Liquidity & relative position (LIVE — R-J / Q5 / R-A / R-F):**")
        L.append("")
        L.append("| Metric | Value |")
        L.append("|--------|-------|")
        L.append(f"| TAO-depth rank | {m['tao_rank']} / {m['n_priced']} priced subnets "
                 f"(~{m['tao_pct']:.0f}th pct, {m['tao_ratio_median']:.2f}× median {m['tao_median']:,.0f} TAO) |")
        L.append(f"| top-liquidity decile threshold | ≥ {m['tao_top_decile']:,.0f} TAO — "
                 f"SN21 {'in' if m['in_top_decile'] else 'NOT in'} top decile |")
        L.append(f"| price rank | {m['price_rank']} / {m['n_priced']} "
                 f"(~{m['price_pct']:.0f}th pct, median {m['price_median']:.6f}) |")
        L.append(f"| floor proximity | spot **+{m['spot_above_floor_pct']:.1f}%** above {m['floor']:.4f}; "
                 f"{m['n_below_floor']} / {m['n_priced']} subnets below it |")
        L.append("")
        r = m["root"]
        if "error" not in r:
            L.append("**Root-stake concentration (LIVE — R-E / Q2):**")
            L.append("")
            L.append(f"Root subnet (netuid 0): **{r['n']} neurons, ~{r['total']:,.0f} TAO** total. "
                     f"top-1 {r['top1']}% · top-3 {r['top3']}% · **top-4 {r['top4']}%** · "
                     f"top-5 {r['top5']}% · **top-10 {r['top10']}%**.")
            L.append("")

    L.append(f"**Cascade impact** — {cfg['accumulation_days']}-day overhang at "
             f"{cfg['sn21_weight_share']*100:.1f}% weight share "
             f"(~{tao_day:,.1f} TAO/day → {P:,.0f} alpha = {P/A0*100:.2f}% of reserve), sold back over a short window:")
    L.append("")
    L.append(f"| Redeemed | x = sold/reserve | Price impact | Spot after | Breaches floor ({floor:.4f})? |")
    L.append("|----------|------------------|--------------|------------|------------------|")
    for f in (0.10, 0.25, 0.50, 1.00):
        x = (f * P) / A0
        imp = price_impact(x)
        spot_after = p0 * (1 + imp)
        breach = "**YES**" if spot_after <= floor else "no"
        note = f" (+{(spot_after/floor-1)*100:.1f}% above floor)" if (f == 1.00 and spot_after > floor) else ""
        L.append(f"| {f*100:.0f}% | {x*100:.2f}% | {imp*100:.2f}% | {spot_after:.5f} | {breach}{note} |")
    L.append("")
    L.append(f"**Floor-breach analysis (full one-shot cascade).** Overhang of **{x_breach*100:.2f}% of reserve** "
             f"breaches the floor if fully redeemed at once. Days of accumulation to reach that, by weight share:")
    L.append("")
    L.append("| Weight share | alpha/day | Days to breach-capable overhang |")
    L.append("|--------------|-----------|----------------------------------|")
    for s in (0.005, 0.01, 0.02, 0.05):
        a_d = cfg["network_root_div_tao_day"] * s / p0
        x_d = a_d / A0
        days = x_breach / x_d if x_d else float("inf")
        L.append(f"| {s*100:.1f}% | {a_d:,.0f} | **{days:.0f} days** |")
    L.append("")
    L.append(DOC_MARK_END)
    return "\n".join(L)


def write_doc(cfg, source: str, market: dict | None, doc_path: Path = DOC_PATH) -> None:
    text = doc_path.read_text(encoding="utf-8")
    if DOC_MARK_BEGIN not in text or DOC_MARK_END not in text:
        raise RuntimeError(
            f"markers not found in {doc_path}; add a block delimited by\n"
            f"  {DOC_MARK_BEGIN}\n  {DOC_MARK_END}")
    pre = text.split(DOC_MARK_BEGIN, 1)[0]
    post = text.split(DOC_MARK_END, 1)[1]
    block = render_live_block(cfg, source, market)
    doc_path.write_text(pre + block + post, encoding="utf-8")
    print(f"  wrote live-figures block -> {doc_path}")


# ----------------------------------------------------------------------
def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    cfg = dict(INPUTS)
    source = DEFAULTS_SOURCE + " (baked-in defaults)"
    market = None
    if "--live" in argv:
        print("Pulling live SN21 pool + market state from finney …")
        live = fetch_live(NETUID_SN21, resolve_dereg_floor(cfg)[0])
        cfg["alpha_reserve"] = live["pool"]["alpha_reserve"]
        cfg["alpha_price_tao"] = live["pool"]["alpha_price_tao"]
        market = live["market"]
        blk = f"block {live['block']:,}" if live.get("block") else "block ?"
        source = f"live finney all_subnets() @ {blk}"
        print(f"  live alpha_reserve = {cfg['alpha_reserve']:,.0f}")
        print(f"  live tao_reserve   = {live['pool']['tao_reserve']:,.0f}")
        print(f"  live spot price    = {cfg['alpha_price_tao']:.6f} TAO/alpha")

    run(cfg, source=source)

    if "--write-doc" in argv:
        if "--live" not in argv:
            print("\n[--write-doc with baked-in defaults — pass --live for fresh chain values]")
        print("\nUpdating assessment doc …")
        write_doc(cfg, source, market)


if __name__ == "__main__":
    main()
