"""
DRAFT mechanism stub — auto-generated by lab/watcher.py on 2026-06-23 09:24 UTC
Release: v3.4.6-421
Source:  https://github.com/opentensor/subtensor/releases/tag/v3.4.6-421

DO NOT TRUST until a human:
  1. reads the PR/source diff and confirms the exact emission_share formula
     (Action 1 / §4.0 — "read the code, not the blog"),
  2. fills in score() below,
  3. moves this file up to lab/mechanisms/ and adds the `register(...)` call,
  4. re-runs the reproduction gate.
Files in _drafts/ are NOT imported by lab/mechanisms/__init__.py.
"""

from __future__ import annotations


def score(sub: dict, state: dict) -> float:
    """Per-subnet emission score for release v3.4.6-421. SN21's share is this
    normalised across all subnets. FILL THIS IN from the source diff.

    Available per-subnet (see lab/chain_pull.py): alpha_in, tao_in, alpha_issued,
    spot_price, ema_price, alpha_out_emission, tao_in_emission, tempo.
    Global state: tao_weight, root_stake_tao, owner_cut, sn21_miner_burn.
    """
    raise NotImplementedError("Draft stub for v3.4.6-421 — implement from source, then promote.")
